dist: trusty
language: node_js
node_js:
    - "5"
    - "6"
    - "7"
addons:
  firefox: "latest"

before_install:
    - sudo apt-get update -qq
    # Install the requirements for adding repos
    # apt-add-repository is in there
    - sudo apt-get install -qy python-software-properties
    # Add repos
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
    # Add apt-keys for checking the packages
    - wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo apt-get update -qq
    # Install the browsers
    - sudo apt-get install -qy chromium-browser google-chrome-stable

#before_script:
    # Setup xvfb for browsers
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

