version: 2
jobs:
  test-firefox-node-6:
    docker:
      - image: circleci/node:6-browsers
        environment:
          BROWSERS: FirefoxHeadless
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: sudo bash test/docker/firefox-installer.bash latest
      - run: npm install
      - run: npm test
  test-firefox-node-8:
    docker:
      - image: circleci/node:8-browsers
        environment:
          BROWSERS: FirefoxHeadless
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-firefox-node-latest:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          BROWSERS: FirefoxHeadless
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test

  # Chrome tests
  test-chrome-node-6:
    docker:
      - image: circleci/node:6-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-chrome-node-8:
    docker:
      - image: circleci/node:8-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-chrome-node-latest:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test-firefox-node-6
#      - test-firefox-node-8
#      - test-firefox-node-latest
#      - test-chrome-node-6
#      - test-chrome-node-8
#      - test-chrome-node-latest
