version: 2
jobs:
  test-firefox-node-6:
    docker:
      - image: bisentenialwrug/videojs-externals:latest
    steps:
      - run: sudo apt-get -qqy update
      - run: sudo apt-get -qqy install ubuntu-restricted-addons pulseaudio libpulse0
      - checkout
      - run:
          shell: /bin/bash --login -eo pipefail
          command: npm install
      - run: pulseaudio --start --daemonize --fail
      - run: pactl load-module module-null-sink
      - run:
          shell: /bin/bash --login -eo pipefail
          command: BROWSERS=MyFirefoxHeadless EX_SPECS=dailymotion:mixcloud grunt test
  test-firefox-node-8:
    docker:
      - image: bisentenialwrug/videojs-externals:latest
        environment:
          BROWSERS: MyFirefoxHeadless
          EX_SPECS: dailymotion:mixcloud
    steps:
      - run: sudo apt-get -qqy update
      - run: sudo apt-get -qqy install ubuntu-restricted-addons pulseaudio libpulse0
      - checkout
      - run:
          shell: /bin/bash --login -eo pipefail
          command: nvm install 8 && nvm alias default 8
      - run:
          shell: /bin/bash --login -eo pipefail
          command: npm install -g grunt-cli
      - run:
          shell: /bin/bash --login -eo pipefail
          command: npm install
      - run: pulseaudio --start --daemonize --fail
      - run: pactl load-module module-null-sink
      - run:
          shell: /bin/bash --login -eo pipefail
          command: BROWSERS=MyFirefoxHeadless EX_SPECS=dailymotion:mixcloud grunt test
  test-firefox-node-latest:
    docker:
      - image: bisentenialwrug/videojs-externals:latest
        environment:
          BROWSERS: MyFirefoxHeadless
          EX_SPECS: dailymotion:mixcloud
    steps:
      - run: sudo apt-get -qqy update
      - run: sudo apt-get -qqy install ubuntu-restricted-addons pulseaudio libpulse0
      - checkout
      - run:
          shell: /bin/bash --login -eo pipefail
          command: nvm install stable && nvm alias default stable
      - run:
          shell: /bin/bash --login -eo pipefail
          command: npm install -g grunt-cli
      - run:
          shell: /bin/bash --login -eo pipefail
          command: npm install
      - run: pulseaudio --start --daemonize --fail
      - run: pactl load-module module-null-sink
      - run:
          shell: /bin/bash --login -eo pipefail
          command: BROWSERS=MyFirefoxHeadless EX_SPECS=dailymotion:mixcloud grunt test

  # Chrome tests
  test-chrome-node-6:
    docker:
      - image: circleci/node:6-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-chrome-node-8:
    docker:
      - image: circleci/node:8-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion:mixcloud
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-chrome-node-latest:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          BROWSERS: Chrome
          EX_SPECS: dailymotion:mixcloud
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test-firefox-node-6
      - test-firefox-node-8
      - test-firefox-node-latest
      - test-chrome-node-6
      - test-chrome-node-8
      - test-chrome-node-latest
